AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  SSMNamespace:
    Type: String
    Default: /openbrighton/main
    Description: SSM namespace prefix for API Gateway parameters

  ApiGatewayId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /openbrighton/main/api-gateway/id

  LambdaS3Bucket:
    Type: String
    Description: S3 bucket containing the Lambda deployment package

  LambdaS3Key:
    Type: String
    Default: bootstrap
    Description: S3 key for the Lambda deployment package

  LambdaHandler:
    Type: String
    Default: main
    Description: Lambda handler (for Go, usually 'main')

  StageName:
    Type: String
    Default: v1
    Description: API Gateway stage name

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaCloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-GraphQLApi"
      Handler: !Ref LambdaHandler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Ref LambdaS3Key
      Runtime: provided.al2
      Timeout: 30
      MemorySize: 256

  ApiGatewayLambdaIntegration:
    Type: AWS::ApiGateway::Deployment
    DependsOn: LambdaFunction
    Properties:
      RestApiId: !Ref ApiGatewayId
      StageName: !Ref StageName
