name: Primary

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install gqlgen
        run: go install github.com/99designs/gqlgen@latest

      - name: Generate GraphQL code
        run: go run github.com/99designs/gqlgen generate

      - name: Build static Linux binary for Lambda (Amazon Linux 2)
        run: |
          docker run --rm -v "$PWD":/app -w /app amazonlinux:2 bash -c "\
            yum install -y curl tar gzip && \
            curl -LO https://go.dev/dl/go1.23.0.linux-amd64.tar.gz && \
            tar -C /usr/local -xzf go1.23.0.linux-amd64.tar.gz && \
            export PATH=/usr/local/go/bin:\$PATH && \
            export GOOS=linux GOARCH=amd64 CGO_ENABLED=0 && \
            go version && \
            go build -o bootstrap server.go"
      - name: Inspect binary
        run: |
          file bootstrap
          ldd bootstrap || echo "Static binary (ldd failed as expected)"
      - name: Upload Lambda artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-binary
          path: bootstrap

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set Variables
        run: |
          echo "STACK_NAME=openbrighton-main-graphql" >> $GITHUB_ENV
          echo "TEMPLATE=./infra/template.yml" >> $GITHUB_ENV
          echo "BUCKET_NAME=openbrighton-main-graphql-artifacts" >> $GITHUB_ENV

      - name: Create S3 bucket (idempotent)
        run: |
          aws s3api create-bucket --bucket "$BUCKET_NAME" --region "$AWS_REGION" 2>&1 | grep -v 'BucketAlreadyOwnedByYou'

      - name: Download Lambda artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda-binary

      - name: Zip Lambda binary
        run: zip bootstrap.zip bootstrap
      - name: Upload Lambda binary to S3
        run: |
          aws s3 cp bootstrap.zip s3://$BUCKET_NAME/bootstrap.zip

      - name: Validate CloudFormation template
        run: aws cloudformation validate-template --template-body file://$TEMPLATE

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file $TEMPLATE \
            --stack-name $STACK_NAME \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --parameter-overrides LambdaS3Bucket=$BUCKET_NAME LambdaS3Key=bootstrap.zip
